name: Documentation CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deployment to Github-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          # DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      
      - name: Set-up git
        run: |
          git config --global user.name "sandab-rumsan"
          git config --global user.email "sandab@rumsan.net"

      - name: Build App
        run: |
          yarn
          yarn run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
