name: Dev CI/CD
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  CI: false

jobs:
  build-test:
    name: install dependencies & test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: |
          yarn install

      - name: build react app
        run: |
          yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build && push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' || false }}
          tags: esatya/rahat-docs:dev
